from enum import Enum

class MissingState(str, Enum):
    CONFIRMED_PRESENT = "CONFIRMED_PRESENT"
    CONFIRMED_ABSENT = "CONFIRMED_ABSENT"
    UNKNOWN = "UNKNOWN"
    NOT_OBSERVED = "NOT_OBSERVED"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    CONFLICTING = "CONFLICTING"
    ENRICHMENT_FAILED = "ENRICHMENT_FAILED"
    NEEDS_MANUAL_RESEARCH = "NEEDS_MANUAL_RESEARCH"

class GateResultState(str, Enum):
    PASS = "PASS"
    FAIL = "FAIL"
    UNKNOWN = "UNKNOWN"
    RESEARCH_REQUIRED = "RESEARCH_REQUIRED"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    NOT_EVALUABLE = "NOT_EVALUABLE"

class CommercialRoleType(str, Enum):
    DIRECT_BUYER = "DIRECT_BUYER"
    CHANNEL = "CHANNEL"
    DISTRIBUTOR = "DISTRIBUTOR"
    RESELLER = "RESELLER"
    SYSTEM_INTEGRATOR = "SYSTEM_INTEGRATOR"
    SPECIFIER = "SPECIFIER"
    CONSULTANT = "CONSULTANT"
    INFLUENCER = "INFLUENCER"
    PROJECT_OWNER = "PROJECT_OWNER"
    PROCUREMENT_BODY = "PROCUREMENT_BODY"
    PARTNER = "PARTNER"
    OTHER_RELEVANT_ROLE = "OTHER_RELEVANT_ROLE"
    ROLE_UNRESOLVED = "ROLE_UNRESOLVED"
    HARD_NEGATIVE = "HARD_NEGATIVE"

class OperationalStatus(str, Enum):
    CONTACT_NOW = "CONTACT_NOW"
    INVESTIGATE_NOW = "INVESTIGATE_NOW"
    NURTURE = "NURTURE"
    LOW_PRIORITY = "LOW_PRIORITY"
    DISQUALIFIED = "DISQUALIFIED"
    SCORING_PENDING = "SCORING_PENDING"
    SCORING_ERROR = "SCORING_ERROR"

class OutcomeState(str, Enum):
    DISCOVERED = "DISCOVERED"
    SHOWN = "SHOWN"
    VIEWED = "VIEWED"
    ADDED_TO_CRM = "ADDED_TO_CRM"
    CONTACTED = "CONTACTED"
    RESPONDED = "RESPONDED"
    QUALIFIED = "QUALIFIED"
    MEETING = "MEETING"
    PROPOSAL = "PROPOSAL"
    WON = "WON"
    LOST = "LOST"
    NURTURE = "NURTURE"
    REJECTED = "REJECTED"

class QualificationStatus(str, Enum):
    ELIGIBLE_FOR_SCORING = "ELIGIBLE_FOR_SCORING"
    DISQUALIFIED = "DISQUALIFIED"
    PENDING_ENTITY_RESOLUTION = "PENDING_ENTITY_RESOLUTION"
    SCORING_PENDING = "SCORING_PENDING"
    SCORING_ERROR = "SCORING_ERROR"
