import { supabase } from "@/integrations/supabase/client";

export class CitationAwareResponseEngine {
  /**
   * Scans the raw LLM response for citation markers (e.g., [Source: ACTION_INTELLIGENCE])
   * and logs them against the evidence records in the database.
   */
  static async processCitations(messageId: string, packageId: string, rawResponse: string) {
    // 1. Regex to find markdown citations generated by the LLM
    const citationRegex = /\[Source:\s*([^\]]+)\]/g;
    const matches = [...rawResponse.matchAll(citationRegex)];

    for (const match of matches) {
      const sourceSystem = match[1];

      // 2. Look up the specific evidence ID from the context package
      const { data: evidence } = await supabase
        .from('context_evidence')
        .select('id')
        .eq('package_id', packageId)
        .eq('source_system', sourceSystem)
        .limit(1)
        .maybeSingle();

      // 3. Save the citation link
      if (evidence) {
        await supabase.from('conversation_citations').insert({
          message_id: messageId,
          evidence_id: evidence.id,
          citation_text: match[0]
        });
      }
    }
  }
}
